### ISSUE TITLE
Issue with the "Download Selected as Zip" function

### ISSUE THREAD

**Issue by ChiragAgg5k** [actuallyakshat/zipit#1]
Hey there. Great application btw. I was just testing it out and found out there was an issue with the zip functionality, particularly its returning a corrupted version of the file uploaded. Here's what i uploaded and what i got:

<img width="329" alt="Screenshot 2024-05-30 at 5 32 19 PM" src="https://github.com/actuallyakshat/zipit/assets/110609663/4f542e50-d6ad-4c61-93f6-5af7306a04ed">
<img width="256" alt="Screenshot 2024-05-30 at 5 32 35 PM" src="https://github.com/actuallyakshat/zipit/assets/110609663/b5f34ba0-98d4-46fc-9035-8def6a7f2a4f">
<img width="259" alt="Screenshot 2024-05-30 at 5 32 47 PM" src="https://github.com/actuallyakshat/zipit/assets/110609663/68b318b6-27bf-439b-8271-af6bac48cdd6">

Although downloading the file individually worked, even though instead of directly downloading it opened the image file on my browser (not sure if that should be intended)

Also i saw someone upload a meme on my private room while i was experimenting... if it was you then cool 😅. If not maybe look a bit into security. 

Again nice project!

**Comment by actuallyakshat** [comment]
Hey Chirag!
Thank you for taking the time and bringing these issues to my notice. I was able to resolve all of them, pretty silly mistakes on my part. The meme showing up in your room was indeed me but I uploaded it in a separate room, I hadn't handled filtering out broadcasts that belonged to different rooms. The application should pretty much work as expected now. Once again, thanks for your feedback, it helped me a lot.
